version: '2'
services:
 webpack:
    build:
      context: .
      dockerfile: docker.webpack
    image: haiku
    container_name: haiku-container
    ports:
      - "3000:3000" ## webpack dev server
      - "9000:9000"
    volumes:
      - .:/haiku